-- 0012 agent — conversaciones del agente de IA, reparto entre vendedores y
-- contexto interno 'agent'. Ver lamelas-agent/docs/contrato-agente-api.md v2.1
-- y modelo-datos-agente.md §1.
--
-- El agente corre en n8n (E1) y le pega a la API con una API key de scope
-- agent:read / agent:write. Del lado de la BD es un contexto más, como auth,
-- worker y export: nunca derivado de input del request, siempre con el tenant
-- de la key fijado.

-- ── Enums ────────────────────────────────────────────────────────────────────
create type conversacion_canal as enum ('whatsapp', 'web');
create type conversacion_estado as enum ('bot', 'esperando_humano', 'humano', 'cerrada');
create type mensaje_rol as enum ('lead', 'agente_ia', 'vendedor', 'sistema');
create type mensaje_tipo as enum ('texto', 'audio', 'imagen', 'documento', 'plantilla');
create type handoff_resultado as enum ('pendiente', 'tomado', 'timeout_reasignado', 'rechazado');
create type nota_origen as enum ('humano', 'agente');

-- Lo que quiere el LEAD, mirado desde el lead. Ojo: es otra cosa que el enum
-- `operacion` de properties ('venta' | 'alquiler'), que mira desde la
-- inmobiliaria. Un lead que quiere vender no matchea ninguna propiedad del
-- inventario y es justamente el caso que hoy se pierde.
create type lead_intencion as enum ('comprar', 'alquilar', 'vender', 'tasar', 'consulta');
create type lead_temperatura as enum ('fria', 'tibia', 'caliente');

-- ── Conversaciones ───────────────────────────────────────────────────────────
create table conversations (
  id          uuid primary key default gen_random_uuid(),
  tenant_id   uuid not null references tenants(id),
  lead_id     uuid not null references leads(id) on delete cascade,
  canal       conversacion_canal not null,
  canal_ref   text not null,                 -- tel E.164 o id de sesión web
  estado      conversacion_estado not null default 'bot',
  vendedor_id uuid references users(id),

  -- Perfil de búsqueda del lead (contrato §4.3). Se extrae del structured
  -- output junto con `resumen`. Va en columnas y no solo dentro del jsonb
  -- porque el panel lo filtra y las métricas lo agrupan.
  intencion       lead_intencion,
  tipo_propiedad  text[],
  ciudad          text,
  zonas           text[],
  presupuesto_min numeric(14, 2),
  presupuesto_max numeric(14, 2),
  moneda          text check (moneda in ('ARS', 'USD')),
  dormitorios_min int,
  property_id     uuid references properties(id) on delete set null,
  temperatura     lead_temperatura,

  resumen     jsonb,                          -- brief completo para el vendedor
  resumen_at  timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Una sola conversación viva por teléfono: es lo que hace idempotente al
-- POST /v1/agent/conversations y evita que cada mensaje abra un lead nuevo.
create unique index conversations_activa_uq
  on conversations (tenant_id, canal, canal_ref)
  where estado <> 'cerrada';

create index idx_conversations_lead on conversations (lead_id);
create index idx_conversations_tenant_estado on conversations (tenant_id, estado);
create index idx_conversations_vendedor on conversations (vendedor_id);

create trigger trg_conversations_updated_at
  before update on conversations
  for each row execute function set_updated_at();

-- ── Mensajes ─────────────────────────────────────────────────────────────────
create table conversation_messages (
  -- 'by default' y no 'always': Prisma omite la columna al insertar, pero
  -- 'always' rechazaría cualquier INSERT que la mande y no vale el riesgo.
  id              bigint generated by default as identity primary key,
  tenant_id       uuid not null references tenants(id),
  conversation_id uuid not null references conversations(id) on delete cascade,
  rol             mensaje_rol not null,
  tipo            mensaje_tipo not null default 'texto',
  contenido       text not null,              -- texto o transcripción del audio
  media_url       text,
  meta            jsonb,                      -- ids de Meta, tokens, tool calls
  created_at      timestamptz not null default now()
);

create index idx_conv_messages_conv on conversation_messages (conversation_id, created_at);

-- ── Vendedores en el reparto ─────────────────────────────────────────────────
-- El reparto es equitativo entre TODOS los vendedores activos (decisión
-- 2026-07-28): sin zonas, sin especialidades, sin preferir al que cargó la
-- propiedad. Esta tabla existe para poder sacar a alguien del reparto
-- (vacaciones) sin desactivarle el usuario del panel.
create table vendedores_agente (
  user_id               uuid primary key references users(id) on delete cascade,
  tenant_id             uuid not null references tenants(id),
  activo                boolean not null default true,
  ultimo_asignado_at    timestamptz,
  leads_asignados_count int not null default 0
);

-- El índice sostiene la elección del round-robin: activos del tenant ordenados
-- por quién hace más que no recibe.
create index idx_vendedores_agente_reparto
  on vendedores_agente (tenant_id, ultimo_asignado_at nulls first)
  where activo;

-- ── Handoffs (auditoría del reparto, reasignaciones incluidas) ───────────────
create table handoffs (
  id              uuid primary key default gen_random_uuid(),
  tenant_id       uuid not null references tenants(id),
  conversation_id uuid not null references conversations(id) on delete cascade,
  vendedor_id     uuid not null references users(id),
  motivo          text not null,              -- visita | reserva | tasacion | ...
  resultado       handoff_resultado not null default 'pendiente',
  asignado_at     timestamptz not null default now(),
  tomado_at       timestamptz
);

create index idx_handoffs_conv on handoffs (conversation_id, asignado_at desc);

-- Los pendientes son los que mira el cron de timeout: índice parcial, que es
-- la parte chica de la tabla.
create index idx_handoffs_pendientes
  on handoffs (asignado_at)
  where resultado = 'pendiente';

-- ── Notas del agente ─────────────────────────────────────────────────────────
-- El resumen del handoff se guarda como nota del lead para que el vendedor lo
-- vea donde ya mira. Pero el agente no es un usuario: user_id pasa a ser
-- nullable y aparece `origen`. Se descartó el "usuario de servicio" porque
-- ensuciaría /equipo, el reparto y las métricas por vendedor.
alter table lead_notes alter column user_id drop not null;
alter table lead_notes add column origen nota_origen not null default 'humano';

alter table lead_notes add constraint lead_notes_autor_coherente check (
  (origen = 'humano' and user_id is not null)
  or (origen = 'agente' and user_id is null)
);

-- ── Contexto interno 'agent' ─────────────────────────────────────────────────
create function is_agent_ctx() returns boolean language sql stable as
  $$ select ctx_rol() = 'agent' $$;

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table conversations enable row level security;
alter table conversation_messages enable row level security;
alter table vendedores_agente enable row level security;
alter table handoffs enable row level security;

-- conversations: el agente opera dentro del tenant de su key; el admin ve todo
-- lo del tenant; el vendedor ve las suyas o las del lead que tiene asignado.
create policy conversations_select on conversations for select using (
  is_super_admin()
  or (tenant_id = ctx_tenant_id() and is_agent_ctx())
  or (tenant_id = ctx_tenant_id() and ctx_rol() = 'admin')
  or (
    tenant_id = ctx_tenant_id() and ctx_rol() = 'agente'
    and (
      vendedor_id = ctx_user_id()
      or exists (select 1 from leads l where l.id = lead_id and l.assigned_to = ctx_user_id())
    )
  )
);

create policy conversations_insert on conversations for insert with check (
  tenant_id = ctx_tenant_id() and (is_agent_ctx() or ctx_rol() = 'admin')
);

-- Update: el agente (estado, resumen, perfil) y el vendedor que la tiene
-- (tomar / liberar el chat).
create policy conversations_update on conversations for update using (
  is_super_admin()
  or (tenant_id = ctx_tenant_id() and is_agent_ctx())
  or (tenant_id = ctx_tenant_id() and ctx_rol() = 'admin')
  or (tenant_id = ctx_tenant_id() and ctx_rol() = 'agente' and vendedor_id = ctx_user_id())
) with check (tenant_id = ctx_tenant_id());

-- conversation_messages: hereda la visibilidad de su conversación (la subquery
-- pasa por conversations_select).
create policy conv_messages_select on conversation_messages for select using (
  is_super_admin()
  or exists (select 1 from conversations c where c.id = conversation_id)
);

create policy conv_messages_insert on conversation_messages for insert with check (
  tenant_id = ctx_tenant_id()
  and exists (select 1 from conversations c where c.id = conversation_id)
  and (is_agent_ctx() or ctx_rol() in ('admin', 'agente'))
);

-- Sin update ni delete: el historial es auditable y no se reescribe.

-- vendedores_agente: el agente lee para repartir y actualiza el turno; el
-- admin gestiona la disponibilidad; el vendedor se ve a sí mismo.
create policy vendedores_agente_select on vendedores_agente for select using (
  is_super_admin()
  or (tenant_id = ctx_tenant_id() and is_agent_ctx())
  or (tenant_id = ctx_tenant_id() and ctx_rol() = 'admin')
  or (tenant_id = ctx_tenant_id() and ctx_rol() = 'agente' and user_id = ctx_user_id())
);

create policy vendedores_agente_insert on vendedores_agente for insert with check (
  tenant_id = ctx_tenant_id() and (ctx_rol() = 'admin' or is_agent_ctx())
);

create policy vendedores_agente_update on vendedores_agente for update using (
  tenant_id = ctx_tenant_id() and (ctx_rol() = 'admin' or is_agent_ctx())
) with check (tenant_id = ctx_tenant_id());

-- handoffs: auditoría. Los crea y cierra el agente; los ve quien ve la
-- conversación.
create policy handoffs_select on handoffs for select using (
  is_super_admin()
  or exists (select 1 from conversations c where c.id = conversation_id)
);

create policy handoffs_insert on handoffs for insert with check (
  tenant_id = ctx_tenant_id() and (is_agent_ctx() or ctx_rol() = 'admin')
);

create policy handoffs_update on handoffs for update using (
  tenant_id = ctx_tenant_id()
  and (
    is_agent_ctx()
    or ctx_rol() = 'admin'
    or (ctx_rol() = 'agente' and vendedor_id = ctx_user_id())
  )
) with check (tenant_id = ctx_tenant_id());

-- ── Accesos que el contexto 'agent' necesita sobre tablas ya existentes ──────
-- Lección de 0003 y 0006, repetida acá a propósito: todo contexto nuevo
-- necesita SELECT sobre lo que Prisma lee, no solo permiso de escribir. Cuando
-- Prisma inserta, después vuelve a leer la fila.

-- properties: la tool buscar_propiedades.
drop policy prop_select on properties;
create policy prop_select on properties for select using (
  is_super_admin()
  or (tenant_id = ctx_tenant_id() and ctx_rol() in ('admin', 'agente', 'public'))
  or (tenant_id = ctx_tenant_id() and is_auth_ctx())
  or (tenant_id = ctx_tenant_id() and is_agent_ctx())
);

-- users: para repartir necesita saber quiénes son los vendedores del tenant.
drop policy users_select on users;
create policy users_select on users for select using (
  is_super_admin()
  or (
    ctx_rol() in ('admin', 'agente')
    and tenant_id is not null
    and tenant_id = ctx_tenant_id()
  )
  or (is_agent_ctx() and tenant_id is not null and tenant_id = ctx_tenant_id())
);

-- leads: el agente da de alta la consulta de WhatsApp, la lee y la actualiza
-- al derivar.
drop policy leads_select on leads;
create policy leads_select on leads for select using (
  is_super_admin()
  or (tenant_id = ctx_tenant_id() and ctx_rol() = 'admin')
  or (tenant_id = ctx_tenant_id() and is_auth_ctx())
  or (tenant_id = ctx_tenant_id() and is_agent_ctx())
  or (
    tenant_id = ctx_tenant_id() and ctx_rol() = 'agente'
    and (
      assigned_to = ctx_user_id()
      or exists (select 1 from properties p where p.id = property_id and p.user_id = ctx_user_id())
    )
  )
);

drop policy leads_insert on leads;
create policy leads_insert on leads for insert with check (
  tenant_id = ctx_tenant_id()
  and (ctx_rol() in ('public', 'auth', 'admin', 'agente') or is_agent_ctx())
);

drop policy leads_update on leads;
create policy leads_update on leads for update using (
  tenant_id = ctx_tenant_id()
  and (
    ctx_rol() = 'admin'
    or is_agent_ctx()
    or (ctx_rol() = 'agente' and assigned_to = ctx_user_id())
  )
) with check (tenant_id = ctx_tenant_id());

-- lead_notes: el agente escribe el resumen del handoff, sin user_id.
drop policy lead_notes_insert on lead_notes;
create policy lead_notes_insert on lead_notes for insert with check (
  tenant_id = ctx_tenant_id()
  and exists (select 1 from leads l where l.id = lead_id)
  and (
    (origen = 'humano' and user_id = ctx_user_id())
    or (origen = 'agente' and is_agent_ctx() and user_id is null)
  )
);

-- ── Grants ───────────────────────────────────────────────────────────────────
grant select, insert, update, delete
  on conversations, conversation_messages, vendedores_agente, handoffs
  to app_rt;

grant usage, select on all sequences in schema public to app_rt;
